/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SkinAnalysisRouteImport } from './routes/skin-analysis'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as StorefrontIdRouteImport } from './routes/storefront.$id'
import { Route as SearchMapRouteImport } from './routes/search.map'
import { Route as ScanResultsRouteImport } from './routes/scan.results'
import { Route as ScanChatRouteImport } from './routes/scan.chat'
import { Route as ScanCaptureRouteImport } from './routes/scan.capture'
import { Route as ScanAnalyzingRouteImport } from './routes/scan.analyzing'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as MedspasSlugRouteImport } from './routes/medspas.$slug'
import { Route as MatchSlugRouteImport } from './routes/match.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as DevRecommendationsRouteImport } from './routes/dev.recommendations'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as BookConsultRouteImport } from './routes/book.consult'
import { Route as ApiGenerateScanPdfRouteImport } from './routes/api/generate-scan-pdf'
import { Route as ApiConsultChatRouteImport } from './routes/api/consult-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TreatmentsSlugIndexRouteImport } from './routes/treatments.$slug.index'
import { Route as TreatmentSlugIndexRouteImport } from './routes/treatment.$slug.index'
import { Route as TreatmentSlugStoryRouteImport } from './routes/treatment.$slug.story'
import { Route as TreatmentSlugReviewsRouteImport } from './routes/treatment.$slug.reviews'
import { Route as ScanConcernKeyRouteImport } from './routes/scan.concern.$key'
import { Route as ApiPublicAnalyzeRouteImport } from './routes/api/public/analyze'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinAnalysisRoute = SkinAnalysisRouteImport.update({
  id: '/skin-analysis',
  path: '/skin-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIdRoute = StorefrontIdRouteImport.update({
  id: '/storefront/$id',
  path: '/storefront/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMapRoute = SearchMapRouteImport.update({
  id: '/search/map',
  path: '/search/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan/results',
  path: '/scan/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanChatRoute = ScanChatRouteImport.update({
  id: '/scan/chat',
  path: '/scan/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCaptureRoute = ScanCaptureRouteImport.update({
  id: '/scan/capture',
  path: '/scan/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanAnalyzingRoute = ScanAnalyzingRouteImport.update({
  id: '/scan/analyzing',
  path: '/scan/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MedspasSlugRoute = MedspasSlugRouteImport.update({
  id: '/medspas/$slug',
  path: '/medspas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchSlugRoute = MatchSlugRouteImport.update({
  id: '/match/$slug',
  path: '/match/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRecommendationsRoute = DevRecommendationsRouteImport.update({
  id: '/dev/recommendations',
  path: '/dev/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultRoute = BookConsultRouteImport.update({
  id: '/book/consult',
  path: '/book/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateScanPdfRoute = ApiGenerateScanPdfRouteImport.update({
  id: '/api/generate-scan-pdf',
  path: '/api/generate-scan-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultChatRoute = ApiConsultChatRouteImport.update({
  id: '/api/consult-chat',
  path: '/api/consult-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugIndexRoute = TreatmentsSlugIndexRouteImport.update({
  id: '/treatments/$slug/',
  path: '/treatments/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentSlugIndexRoute = TreatmentSlugIndexRouteImport.update({
  id: '/treatment/$slug/',
  path: '/treatment/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentSlugStoryRoute = TreatmentSlugStoryRouteImport.update({
  id: '/treatment/$slug/story',
  path: '/treatment/$slug/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentSlugReviewsRoute = TreatmentSlugReviewsRouteImport.update({
  id: '/treatment/$slug/reviews',
  path: '/treatment/$slug/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanConcernKeyRoute = ScanConcernKeyRouteImport.update({
  id: '/scan/concern/$key',
  path: '/scan/concern/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeRoute = ApiPublicAnalyzeRouteImport.update({
  id: '/api/public/analyze',
  path: '/api/public/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/skin-analysis': typeof SkinAnalysisRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/consult-chat': typeof ApiConsultChatRoute
  '/api/generate-scan-pdf': typeof ApiGenerateScanPdfRoute
  '/book/consult': typeof BookConsultRoute
  '/claim/$id': typeof ClaimIdRoute
  '/dev/recommendations': typeof DevRecommendationsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/match/$slug': typeof MatchSlugRoute
  '/medspas/$slug': typeof MedspasSlugRoute
  '/provider/$id': typeof ProviderIdRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/scan/analyzing': typeof ScanAnalyzingRoute
  '/scan/capture': typeof ScanCaptureRoute
  '/scan/chat': typeof ScanChatRoute
  '/scan/results': typeof ScanResultsRoute
  '/search/map': typeof SearchMapRoute
  '/storefront/$id': typeof StorefrontIdRoute
  '/scan/': typeof ScanIndexRoute
  '/search/': typeof SearchIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/scan/concern/$key': typeof ScanConcernKeyRoute
  '/treatment/$slug/reviews': typeof TreatmentSlugReviewsRoute
  '/treatment/$slug/story': typeof TreatmentSlugStoryRoute
  '/treatment/$slug/': typeof TreatmentSlugIndexRoute
  '/treatments/$slug/': typeof TreatmentsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/skin-analysis': typeof SkinAnalysisRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/consult-chat': typeof ApiConsultChatRoute
  '/api/generate-scan-pdf': typeof ApiGenerateScanPdfRoute
  '/book/consult': typeof BookConsultRoute
  '/claim/$id': typeof ClaimIdRoute
  '/dev/recommendations': typeof DevRecommendationsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/match/$slug': typeof MatchSlugRoute
  '/medspas/$slug': typeof MedspasSlugRoute
  '/provider/$id': typeof ProviderIdRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/scan/analyzing': typeof ScanAnalyzingRoute
  '/scan/capture': typeof ScanCaptureRoute
  '/scan/chat': typeof ScanChatRoute
  '/scan/results': typeof ScanResultsRoute
  '/search/map': typeof SearchMapRoute
  '/storefront/$id': typeof StorefrontIdRoute
  '/scan': typeof ScanIndexRoute
  '/search': typeof SearchIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/scan/concern/$key': typeof ScanConcernKeyRoute
  '/treatment/$slug/reviews': typeof TreatmentSlugReviewsRoute
  '/treatment/$slug/story': typeof TreatmentSlugStoryRoute
  '/treatment/$slug': typeof TreatmentSlugIndexRoute
  '/treatments/$slug': typeof TreatmentsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/skin-analysis': typeof SkinAnalysisRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/consult-chat': typeof ApiConsultChatRoute
  '/api/generate-scan-pdf': typeof ApiGenerateScanPdfRoute
  '/book/consult': typeof BookConsultRoute
  '/claim/$id': typeof ClaimIdRoute
  '/dev/recommendations': typeof DevRecommendationsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/match/$slug': typeof MatchSlugRoute
  '/medspas/$slug': typeof MedspasSlugRoute
  '/provider/$id': typeof ProviderIdRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/scan/analyzing': typeof ScanAnalyzingRoute
  '/scan/capture': typeof ScanCaptureRoute
  '/scan/chat': typeof ScanChatRoute
  '/scan/results': typeof ScanResultsRoute
  '/search/map': typeof SearchMapRoute
  '/storefront/$id': typeof StorefrontIdRoute
  '/scan/': typeof ScanIndexRoute
  '/search/': typeof SearchIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/scan/concern/$key': typeof ScanConcernKeyRoute
  '/treatment/$slug/reviews': typeof TreatmentSlugReviewsRoute
  '/treatment/$slug/story': typeof TreatmentSlugStoryRoute
  '/treatment/$slug/': typeof TreatmentSlugIndexRoute
  '/treatments/$slug/': typeof TreatmentsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/skin-analysis'
    | '/terms'
    | '/api/chat'
    | '/api/consult-chat'
    | '/api/generate-scan-pdf'
    | '/book/consult'
    | '/claim/$id'
    | '/dev/recommendations'
    | '/learn/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/match/$slug'
    | '/medspas/$slug'
    | '/provider/$id'
    | '/providers/$slug'
    | '/scan/analyzing'
    | '/scan/capture'
    | '/scan/chat'
    | '/scan/results'
    | '/search/map'
    | '/storefront/$id'
    | '/scan/'
    | '/search/'
    | '/treatments/'
    | '/api/public/analyze'
    | '/scan/concern/$key'
    | '/treatment/$slug/reviews'
    | '/treatment/$slug/story'
    | '/treatment/$slug/'
    | '/treatments/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/skin-analysis'
    | '/terms'
    | '/api/chat'
    | '/api/consult-chat'
    | '/api/generate-scan-pdf'
    | '/book/consult'
    | '/claim/$id'
    | '/dev/recommendations'
    | '/learn/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/match/$slug'
    | '/medspas/$slug'
    | '/provider/$id'
    | '/providers/$slug'
    | '/scan/analyzing'
    | '/scan/capture'
    | '/scan/chat'
    | '/scan/results'
    | '/search/map'
    | '/storefront/$id'
    | '/scan'
    | '/search'
    | '/treatments'
    | '/api/public/analyze'
    | '/scan/concern/$key'
    | '/treatment/$slug/reviews'
    | '/treatment/$slug/story'
    | '/treatment/$slug'
    | '/treatments/$slug'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/skin-analysis'
    | '/terms'
    | '/api/chat'
    | '/api/consult-chat'
    | '/api/generate-scan-pdf'
    | '/book/consult'
    | '/claim/$id'
    | '/dev/recommendations'
    | '/learn/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/match/$slug'
    | '/medspas/$slug'
    | '/provider/$id'
    | '/providers/$slug'
    | '/scan/analyzing'
    | '/scan/capture'
    | '/scan/chat'
    | '/scan/results'
    | '/search/map'
    | '/storefront/$id'
    | '/scan/'
    | '/search/'
    | '/treatments/'
    | '/api/public/analyze'
    | '/scan/concern/$key'
    | '/treatment/$slug/reviews'
    | '/treatment/$slug/story'
    | '/treatment/$slug/'
    | '/treatments/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SkinAnalysisRoute: typeof SkinAnalysisRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConsultChatRoute: typeof ApiConsultChatRoute
  ApiGenerateScanPdfRoute: typeof ApiGenerateScanPdfRoute
  BookConsultRoute: typeof BookConsultRoute
  ClaimIdRoute: typeof ClaimIdRoute
  DevRecommendationsRoute: typeof DevRecommendationsRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MatchSlugRoute: typeof MatchSlugRoute
  MedspasSlugRoute: typeof MedspasSlugRoute
  ProviderIdRoute: typeof ProviderIdRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
  ScanAnalyzingRoute: typeof ScanAnalyzingRoute
  ScanCaptureRoute: typeof ScanCaptureRoute
  ScanChatRoute: typeof ScanChatRoute
  ScanResultsRoute: typeof ScanResultsRoute
  SearchMapRoute: typeof SearchMapRoute
  StorefrontIdRoute: typeof StorefrontIdRoute
  ScanIndexRoute: typeof ScanIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
  ApiPublicAnalyzeRoute: typeof ApiPublicAnalyzeRoute
  ScanConcernKeyRoute: typeof ScanConcernKeyRoute
  TreatmentSlugReviewsRoute: typeof TreatmentSlugReviewsRoute
  TreatmentSlugStoryRoute: typeof TreatmentSlugStoryRoute
  TreatmentSlugIndexRoute: typeof TreatmentSlugIndexRoute
  TreatmentsSlugIndexRoute: typeof TreatmentsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-analysis': {
      id: '/skin-analysis'
      path: '/skin-analysis'
      fullPath: '/skin-analysis'
      preLoaderRoute: typeof SkinAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/$id': {
      id: '/storefront/$id'
      path: '/storefront/$id'
      fullPath: '/storefront/$id'
      preLoaderRoute: typeof StorefrontIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/map': {
      id: '/search/map'
      path: '/search/map'
      fullPath: '/search/map'
      preLoaderRoute: typeof SearchMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/scan/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/chat': {
      id: '/scan/chat'
      path: '/scan/chat'
      fullPath: '/scan/chat'
      preLoaderRoute: typeof ScanChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/capture': {
      id: '/scan/capture'
      path: '/scan/capture'
      fullPath: '/scan/capture'
      preLoaderRoute: typeof ScanCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/analyzing': {
      id: '/scan/analyzing'
      path: '/scan/analyzing'
      fullPath: '/scan/analyzing'
      preLoaderRoute: typeof ScanAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medspas/$slug': {
      id: '/medspas/$slug'
      path: '/medspas/$slug'
      fullPath: '/medspas/$slug'
      preLoaderRoute: typeof MedspasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$slug': {
      id: '/match/$slug'
      path: '/match/$slug'
      fullPath: '/match/$slug'
      preLoaderRoute: typeof MatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/recommendations': {
      id: '/dev/recommendations'
      path: '/dev/recommendations'
      fullPath: '/dev/recommendations'
      preLoaderRoute: typeof DevRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/consult': {
      id: '/book/consult'
      path: '/book/consult'
      fullPath: '/book/consult'
      preLoaderRoute: typeof BookConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-scan-pdf': {
      id: '/api/generate-scan-pdf'
      path: '/api/generate-scan-pdf'
      fullPath: '/api/generate-scan-pdf'
      preLoaderRoute: typeof ApiGenerateScanPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consult-chat': {
      id: '/api/consult-chat'
      path: '/api/consult-chat'
      fullPath: '/api/consult-chat'
      preLoaderRoute: typeof ApiConsultChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug/': {
      id: '/treatments/$slug/'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug/'
      preLoaderRoute: typeof TreatmentsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment/$slug/': {
      id: '/treatment/$slug/'
      path: '/treatment/$slug'
      fullPath: '/treatment/$slug/'
      preLoaderRoute: typeof TreatmentSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment/$slug/story': {
      id: '/treatment/$slug/story'
      path: '/treatment/$slug/story'
      fullPath: '/treatment/$slug/story'
      preLoaderRoute: typeof TreatmentSlugStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment/$slug/reviews': {
      id: '/treatment/$slug/reviews'
      path: '/treatment/$slug/reviews'
      fullPath: '/treatment/$slug/reviews'
      preLoaderRoute: typeof TreatmentSlugReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/concern/$key': {
      id: '/scan/concern/$key'
      path: '/scan/concern/$key'
      fullPath: '/scan/concern/$key'
      preLoaderRoute: typeof ScanConcernKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze': {
      id: '/api/public/analyze'
      path: '/api/public/analyze'
      fullPath: '/api/public/analyze'
      preLoaderRoute: typeof ApiPublicAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SkinAnalysisRoute: SkinAnalysisRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConsultChatRoute: ApiConsultChatRoute,
  ApiGenerateScanPdfRoute: ApiGenerateScanPdfRoute,
  BookConsultRoute: BookConsultRoute,
  ClaimIdRoute: ClaimIdRoute,
  DevRecommendationsRoute: DevRecommendationsRoute,
  LearnSlugRoute: LearnSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MatchSlugRoute: MatchSlugRoute,
  MedspasSlugRoute: MedspasSlugRoute,
  ProviderIdRoute: ProviderIdRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
  ScanAnalyzingRoute: ScanAnalyzingRoute,
  ScanCaptureRoute: ScanCaptureRoute,
  ScanChatRoute: ScanChatRoute,
  ScanResultsRoute: ScanResultsRoute,
  SearchMapRoute: SearchMapRoute,
  StorefrontIdRoute: StorefrontIdRoute,
  ScanIndexRoute: ScanIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
  ApiPublicAnalyzeRoute: ApiPublicAnalyzeRoute,
  ScanConcernKeyRoute: ScanConcernKeyRoute,
  TreatmentSlugReviewsRoute: TreatmentSlugReviewsRoute,
  TreatmentSlugStoryRoute: TreatmentSlugStoryRoute,
  TreatmentSlugIndexRoute: TreatmentSlugIndexRoute,
  TreatmentsSlugIndexRoute: TreatmentsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
