/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as StorefrontIdRouteImport } from './routes/storefront.$id'
import { Route as SearchMapRouteImport } from './routes/search.map'
import { Route as ScanResultsRouteImport } from './routes/scan.results'
import { Route as ScanChatRouteImport } from './routes/scan.chat'
import { Route as ScanAnalyzingRouteImport } from './routes/scan.analyzing'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as MedspasSlugRouteImport } from './routes/medspas.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as DevRecommendationsRouteImport } from './routes/dev.recommendations'
import { Route as BookConsultRouteImport } from './routes/book.consult'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TreatmentsSlugIndexRouteImport } from './routes/treatments.$slug.index'
import { Route as TreatmentSlugIndexRouteImport } from './routes/treatment.$slug.index'
import { Route as TreatmentsSlugBookRouteImport } from './routes/treatments.$slug.book'
import { Route as TreatmentSlugStoryRouteImport } from './routes/treatment.$slug.story'
import { Route as ApiPublicAnalyzeRouteImport } from './routes/api/public/analyze'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIdRoute = StorefrontIdRouteImport.update({
  id: '/storefront/$id',
  path: '/storefront/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMapRoute = SearchMapRouteImport.update({
  id: '/search/map',
  path: '/search/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan/results',
  path: '/scan/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanChatRoute = ScanChatRouteImport.update({
  id: '/scan/chat',
  path: '/scan/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanAnalyzingRoute = ScanAnalyzingRouteImport.update({
  id: '/scan/analyzing',
  path: '/scan/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MedspasSlugRoute = MedspasSlugRouteImport.update({
  id: '/medspas/$slug',
  path: '/medspas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRecommendationsRoute = DevRecommendationsRouteImport.update({
  id: '/dev/recommendations',
  path: '/dev/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultRoute = BookConsultRouteImport.update({
  id: '/book/consult',
  path: '/book/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugIndexRoute = TreatmentsSlugIndexRouteImport.update({
  id: '/treatments/$slug/',
  path: '/treatments/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentSlugIndexRoute = TreatmentSlugIndexRouteImport.update({
  id: '/treatment/$slug/',
  path: '/treatment/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugBookRoute = TreatmentsSlugBookRouteImport.update({
  id: '/treatments/$slug/book',
  path: '/treatments/$slug/book',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentSlugStoryRoute = TreatmentSlugStoryRouteImport.update({
  id: '/treatment/$slug/story',
  path: '/treatment/$slug/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeRoute = ApiPublicAnalyzeRouteImport.update({
  id: '/api/public/analyze',
  path: '/api/public/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/book/consult': typeof BookConsultRoute
  '/dev/recommendations': typeof DevRecommendationsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/medspas/$slug': typeof MedspasSlugRoute
  '/provider/$id': typeof ProviderIdRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/scan/analyzing': typeof ScanAnalyzingRoute
  '/scan/chat': typeof ScanChatRoute
  '/scan/results': typeof ScanResultsRoute
  '/search/map': typeof SearchMapRoute
  '/storefront/$id': typeof StorefrontIdRoute
  '/scan/': typeof ScanIndexRoute
  '/search/': typeof SearchIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/treatment/$slug/story': typeof TreatmentSlugStoryRoute
  '/treatments/$slug/book': typeof TreatmentsSlugBookRoute
  '/treatment/$slug/': typeof TreatmentSlugIndexRoute
  '/treatments/$slug/': typeof TreatmentsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/book/consult': typeof BookConsultRoute
  '/dev/recommendations': typeof DevRecommendationsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/medspas/$slug': typeof MedspasSlugRoute
  '/provider/$id': typeof ProviderIdRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/scan/analyzing': typeof ScanAnalyzingRoute
  '/scan/chat': typeof ScanChatRoute
  '/scan/results': typeof ScanResultsRoute
  '/search/map': typeof SearchMapRoute
  '/storefront/$id': typeof StorefrontIdRoute
  '/scan': typeof ScanIndexRoute
  '/search': typeof SearchIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/treatment/$slug/story': typeof TreatmentSlugStoryRoute
  '/treatments/$slug/book': typeof TreatmentsSlugBookRoute
  '/treatment/$slug': typeof TreatmentSlugIndexRoute
  '/treatments/$slug': typeof TreatmentsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/book/consult': typeof BookConsultRoute
  '/dev/recommendations': typeof DevRecommendationsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/medspas/$slug': typeof MedspasSlugRoute
  '/provider/$id': typeof ProviderIdRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/scan/analyzing': typeof ScanAnalyzingRoute
  '/scan/chat': typeof ScanChatRoute
  '/scan/results': typeof ScanResultsRoute
  '/search/map': typeof SearchMapRoute
  '/storefront/$id': typeof StorefrontIdRoute
  '/scan/': typeof ScanIndexRoute
  '/search/': typeof SearchIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/treatment/$slug/story': typeof TreatmentSlugStoryRoute
  '/treatments/$slug/book': typeof TreatmentsSlugBookRoute
  '/treatment/$slug/': typeof TreatmentSlugIndexRoute
  '/treatments/$slug/': typeof TreatmentsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/api/chat'
    | '/book/consult'
    | '/dev/recommendations'
    | '/learn/$slug'
    | '/medspas/$slug'
    | '/provider/$id'
    | '/providers/$slug'
    | '/scan/analyzing'
    | '/scan/chat'
    | '/scan/results'
    | '/search/map'
    | '/storefront/$id'
    | '/scan/'
    | '/search/'
    | '/treatments/'
    | '/api/public/analyze'
    | '/treatment/$slug/story'
    | '/treatments/$slug/book'
    | '/treatment/$slug/'
    | '/treatments/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/api/chat'
    | '/book/consult'
    | '/dev/recommendations'
    | '/learn/$slug'
    | '/medspas/$slug'
    | '/provider/$id'
    | '/providers/$slug'
    | '/scan/analyzing'
    | '/scan/chat'
    | '/scan/results'
    | '/search/map'
    | '/storefront/$id'
    | '/scan'
    | '/search'
    | '/treatments'
    | '/api/public/analyze'
    | '/treatment/$slug/story'
    | '/treatments/$slug/book'
    | '/treatment/$slug'
    | '/treatments/$slug'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/api/chat'
    | '/book/consult'
    | '/dev/recommendations'
    | '/learn/$slug'
    | '/medspas/$slug'
    | '/provider/$id'
    | '/providers/$slug'
    | '/scan/analyzing'
    | '/scan/chat'
    | '/scan/results'
    | '/search/map'
    | '/storefront/$id'
    | '/scan/'
    | '/search/'
    | '/treatments/'
    | '/api/public/analyze'
    | '/treatment/$slug/story'
    | '/treatments/$slug/book'
    | '/treatment/$slug/'
    | '/treatments/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ApiChatRoute: typeof ApiChatRoute
  BookConsultRoute: typeof BookConsultRoute
  DevRecommendationsRoute: typeof DevRecommendationsRoute
  LearnSlugRoute: typeof LearnSlugRoute
  MedspasSlugRoute: typeof MedspasSlugRoute
  ProviderIdRoute: typeof ProviderIdRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
  ScanAnalyzingRoute: typeof ScanAnalyzingRoute
  ScanChatRoute: typeof ScanChatRoute
  ScanResultsRoute: typeof ScanResultsRoute
  SearchMapRoute: typeof SearchMapRoute
  StorefrontIdRoute: typeof StorefrontIdRoute
  ScanIndexRoute: typeof ScanIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
  ApiPublicAnalyzeRoute: typeof ApiPublicAnalyzeRoute
  TreatmentSlugStoryRoute: typeof TreatmentSlugStoryRoute
  TreatmentsSlugBookRoute: typeof TreatmentsSlugBookRoute
  TreatmentSlugIndexRoute: typeof TreatmentSlugIndexRoute
  TreatmentsSlugIndexRoute: typeof TreatmentsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/$id': {
      id: '/storefront/$id'
      path: '/storefront/$id'
      fullPath: '/storefront/$id'
      preLoaderRoute: typeof StorefrontIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/map': {
      id: '/search/map'
      path: '/search/map'
      fullPath: '/search/map'
      preLoaderRoute: typeof SearchMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/scan/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/chat': {
      id: '/scan/chat'
      path: '/scan/chat'
      fullPath: '/scan/chat'
      preLoaderRoute: typeof ScanChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/analyzing': {
      id: '/scan/analyzing'
      path: '/scan/analyzing'
      fullPath: '/scan/analyzing'
      preLoaderRoute: typeof ScanAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medspas/$slug': {
      id: '/medspas/$slug'
      path: '/medspas/$slug'
      fullPath: '/medspas/$slug'
      preLoaderRoute: typeof MedspasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/recommendations': {
      id: '/dev/recommendations'
      path: '/dev/recommendations'
      fullPath: '/dev/recommendations'
      preLoaderRoute: typeof DevRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/consult': {
      id: '/book/consult'
      path: '/book/consult'
      fullPath: '/book/consult'
      preLoaderRoute: typeof BookConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug/': {
      id: '/treatments/$slug/'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug/'
      preLoaderRoute: typeof TreatmentsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment/$slug/': {
      id: '/treatment/$slug/'
      path: '/treatment/$slug'
      fullPath: '/treatment/$slug/'
      preLoaderRoute: typeof TreatmentSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug/book': {
      id: '/treatments/$slug/book'
      path: '/treatments/$slug/book'
      fullPath: '/treatments/$slug/book'
      preLoaderRoute: typeof TreatmentsSlugBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment/$slug/story': {
      id: '/treatment/$slug/story'
      path: '/treatment/$slug/story'
      fullPath: '/treatment/$slug/story'
      preLoaderRoute: typeof TreatmentSlugStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze': {
      id: '/api/public/analyze'
      path: '/api/public/analyze'
      fullPath: '/api/public/analyze'
      preLoaderRoute: typeof ApiPublicAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ApiChatRoute: ApiChatRoute,
  BookConsultRoute: BookConsultRoute,
  DevRecommendationsRoute: DevRecommendationsRoute,
  LearnSlugRoute: LearnSlugRoute,
  MedspasSlugRoute: MedspasSlugRoute,
  ProviderIdRoute: ProviderIdRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
  ScanAnalyzingRoute: ScanAnalyzingRoute,
  ScanChatRoute: ScanChatRoute,
  ScanResultsRoute: ScanResultsRoute,
  SearchMapRoute: SearchMapRoute,
  StorefrontIdRoute: StorefrontIdRoute,
  ScanIndexRoute: ScanIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
  ApiPublicAnalyzeRoute: ApiPublicAnalyzeRoute,
  TreatmentSlugStoryRoute: TreatmentSlugStoryRoute,
  TreatmentsSlugBookRoute: TreatmentsSlugBookRoute,
  TreatmentSlugIndexRoute: TreatmentSlugIndexRoute,
  TreatmentsSlugIndexRoute: TreatmentsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
